### ISSUE TITLE
Cache while clickhouse away

### ISSUE THREAD

**Issue by denser** [ircop/natlog#1]
Hello, could you add some journal for cache if clickhouse away unexpectedly?
Preferred use file as storage.

I mean cache to file this 100k messages and then push it to ch. If ch is away - create next file and try to push files periodically.

**Comment by ircop** [comment]
I'm afraid it will be too heavy stuff for such proxy.

In my environment there are ~100k records per second (i know much heavier installations), and fast structurred writing/reading them to disk may be too slow.

Maybe it will be better to setup CH cluster/replica if data loss is critical

**Comment by denser** [comment]
Cluster in 6+ TB of data is harder choice :) Better making stash(fluentd?) or similar. May be in future?

**Comment by denser** [comment]
Opening for myself such great app as  Vector, now migrating from this.
